name: Toxic CSWO All Shows

on:
  workflow_dispatch:

jobs:
  toxic-cswo:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install curl_cffi gspread google-auth pytz playwright

      - name: Install Chromium
        run: |
          python -m playwright install chromium
          python -m playwright install-deps chromium

      - name: Run Toxic CSWO Tracker
        env:
          SPREADSHEET_ID: "1zzp8T0ergvrIcyqutlLTh6bzO2CBwfWT9xoaAMaCOO4"
          GCP_SA_KEY_B64: ${{ secrets.GCP_SA_KEY_B64 }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          python tracker.py
